title: LaraJournal
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://larajournal.github.io/docs

aux_links:
  Template Repository: https://github.com/larajournal/docs
